### ISSUE TITLE
Passer les repos au standard PSR-2

### ISSUE THREAD

**Issue by cyrilphoenix71** [Jeedom-Plugins-Extra/plugin-veolia_eau#37]
Nettoyer le code en respactant le standard PSR-2 et en suivant : https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/Bonnes-pratiques-pour-les-plugins

**Comment by damien916** [comment]
https://github.com/Jeedom-Plugins-Extra/plugin-veolia_eau/commit/f09f4f6424a262fd3c768478e070dc8dd935ffe0
