### ISSUE TITLE
Vérification  et correction  de displayExeption par displayException

### ISSUE THREAD

**Issue by byackee** [Jeedom-Plugins-Extra/plugin-veolia_eau#48]
Suite au PR https://github.com/jeedom/core/issues/971, veuillez vérifier la bonne orthographe de displayException

**Comment by damien916** [comment]
https://github.com/Jeedom-Plugins-Extra/plugin-veolia_eau/commit/560d392bad2a3fb41d33832c5150fe9bf6e9321b
