### ISSUE TITLE
Gerer les non mesurée pour $website=2 en utilisant le csv

### ISSUE THREAD

**Issue by rjullien** [Jeedom-Plugins-Extra/plugin-veolia_eau#51]
## Description
Veolia sud est genere des valeur abérrantes: 2 valeurs le meme jour: 150 et -100000 et le lendemain +99000 par exemple, ce qui se traduit par non mesuré dans le html et ces valeurs dans le csv
## Etapes à reproduire (pour les bugs)
1. Attendre que le cas se produise sur le site

## Proposition de solution (optionnel):
gerer le cas avec le csv

## Environnement:
* **Version Jeedom**:
* **Platform**:
* **Version du Plugin**:

**Comment by rjullien** [comment]
Je bosse sur cette issue tu peux me l'assigner.

**Comment by rjullien** [comment]
Livré

**Comment by damien916** [comment]
Merci, déployé en bêta, à tester
