### ISSUE TITLE
Gerer eau-du-grand-lyon

### ISSUE THREAD

**Issue by rjullien** [Jeedom-Plugins-Extra/plugin-veolia_eau#52]
## Description
Gerer eau-du-grand-lyon

Issue pour tracker le pb, j ai une version qui doit marcher dans mon fork

**Comment by rjullien** [comment]
Livré, a tester

**Comment by damien916** [comment]
Merci, déployé en bêta, à tester

**Comment by rjullien** [comment]
J ai recupere un accès a Eau Lyon, il y a un pb sur l'index a cause du fait que le dernier jour du mois est repeté au debut du mois suivant.
Je regarde ca demain soir si j ai le temps

**Comment by damien916** [comment]
ok, top
